indent_width: 4
column_limit: 80
keep_simple_control_block_one_line: false
keep_simple_function_one_line: false
break_after_functioncall_lp: true
break_before_functioncall_rp: true
break_after_functiondef_lp: true
break_before_functiondef_rp: true
line_breaks_after_function_body: 2
